"""empty message

Revision ID: 02087afcac51
Revises: 702bc09c73f9
Create Date: 2020-02-15 18:08:42.024279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02087afcac51'
down_revision = '702bc09c73f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beach_encounter', sa.Column('latitude', sa.Float(precision=5), nullable=True))
    op.add_column('beach_encounter', sa.Column('longitude', sa.Float(precision=5), nullable=True))
    op.drop_column('beach_encounter', 'lat_w')
    op.drop_column('beach_encounter', 'lat_n')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beach_encounter', sa.Column('lat_n', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('beach_encounter', sa.Column('lat_w', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_column('beach_encounter', 'longitude')
    op.drop_column('beach_encounter', 'latitude')
    # ### end Alembic commands ###
