"""empty message

Revision ID: 1e628697674e
Revises: 86f6ff25c4ff
Create Date: 2020-04-16 23:59:58.657857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e628697674e'
down_revision = '86f6ff25c4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounter', sa.Column('img_filename', sa.Text(), nullable=True))
    op.add_column('encounter', sa.Column('pdf_filename', sa.Text(), nullable=True))
    op.drop_constraint('encounter_filename_key', 'encounter', type_='unique')
    op.create_unique_constraint(None, 'encounter', ['pdf_filename'])
    op.create_unique_constraint(None, 'encounter', ['img_filename'])
    op.drop_column('encounter', 'filename')
    op.drop_column('legacy', 'clutch_other_egg_affected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legacy', sa.Column('clutch_other_egg_affected', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('encounter', sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'encounter', type_='unique')
    op.drop_constraint(None, 'encounter', type_='unique')
    op.create_unique_constraint('encounter_filename_key', 'encounter', ['filename'])
    op.drop_column('encounter', 'pdf_filename')
    op.drop_column('encounter', 'img_filename')
    # ### end Alembic commands ###
