"""add clutch table

Revision ID: 3243c092326f
Revises: 
Create Date: 2019-11-04 11:48:20.649566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3243c092326f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clutch',
    sa.Column('clutch_id', sa.Integer(), nullable=False),
    sa.Column('clutch_deposited', sa.Boolean(), nullable=True),
    sa.Column('sand_type', sa.String(length=50), nullable=True),
    sa.Column('placement', sa.String(length=50), nullable=True),
    sa.Column('emergence_date', sa.Date(), nullable=True),
    sa.Column('inventory_date', sa.Date(), nullable=True),
    sa.Column('hidden_stake_in_place', sa.Boolean(), nullable=True),
    sa.Column('obvious_stake_in_place', sa.Boolean(), nullable=True),
    sa.Column('emergence', sa.Boolean(), nullable=True),
    sa.Column('s_can_in_place', sa.Boolean(), nullable=True),
    sa.Column('n_can_in_place', sa.Boolean(), nullable=True),
    sa.Column('predated', sa.Boolean(), nullable=True),
    sa.Column('post_hatch', sa.Boolean(), nullable=True),
    sa.Column('washed_over', sa.Boolean(), nullable=True),
    sa.Column('inundated', sa.Boolean(), nullable=True),
    sa.Column('washed_out', sa.String(length=20), nullable=True),
    sa.Column('washed_out_post_hatch', sa.Boolean(), nullable=True),
    sa.Column('poached', sa.Boolean(), nullable=True),
    sa.Column('inventoried_by', sa.String(length=40), nullable=True),
    sa.Column('entered_by', sa.String(length=40), nullable=True),
    sa.Column('entered_date', sa.Date(), nullable=True),
    sa.Column('verified_by', sa.String(length=40), nullable=True),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('clutch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clutch')
    # ### end Alembic commands ###
