"""empty message

Revision ID: 3527b03f33f5
Revises: 02087afcac51
Create Date: 2020-02-15 18:17:36.237746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3527b03f33f5'
down_revision = '02087afcac51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('encounter', 'metadata_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('encounter', 'metadata_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
