"""empty message

Revision ID: 4422792e6609
Revises: fcafc027ced1
Create Date: 2020-02-15 12:31:53.140701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4422792e6609'
down_revision = 'fcafc027ced1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clutch', sa.Column('eggs_damaged_raccoons', sa.Integer(), nullable=True))
    op.add_column('clutch', sa.Column('eggs_embryo_1_4', sa.Integer(), nullable=True))
    op.add_column('clutch', sa.Column('eggs_embryo_2_4', sa.Integer(), nullable=True))
    op.add_column('clutch', sa.Column('eggs_embryo_3_4', sa.Integer(), nullable=True))
    op.add_column('clutch', sa.Column('eggs_embryo_4_4', sa.Integer(), nullable=True))
    op.drop_column('clutch', 'eggs_damaged_racoons')
    op.drop_column('clutch', 'eggs_2_4_embryo')
    op.drop_column('clutch', 'eggs_1_4_embryo')
    op.drop_column('clutch', 'eggs_3_4_embryo')
    op.drop_column('clutch', 'eggs_4_4_embryo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clutch', sa.Column('eggs_4_4_embryo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clutch', sa.Column('eggs_3_4_embryo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clutch', sa.Column('eggs_1_4_embryo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clutch', sa.Column('eggs_2_4_embryo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clutch', sa.Column('eggs_damaged_racoons', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('clutch', 'eggs_embryo_4_4')
    op.drop_column('clutch', 'eggs_embryo_3_4')
    op.drop_column('clutch', 'eggs_embryo_2_4')
    op.drop_column('clutch', 'eggs_embryo_1_4')
    op.drop_column('clutch', 'eggs_damaged_raccoons')
    # ### end Alembic commands ###
