"""empty message

Revision ID: 5b9fc7ca2214
Revises: ed404691bc7e
Create Date: 2020-02-08 11:41:08.527666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9fc7ca2214'
down_revision = 'ed404691bc7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'samples_id', new_column_name='sample_id')
    op.create_table('sample_tracking',
    sa.Column('sample_tracking_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_tracking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'sample_id', new_column_name='samples_id')
    op.drop_table('sample_tracking')
    # ### end Alembic commands ###
