"""empty message

Revision ID: 702bc09c73f9
Revises: 4422792e6609
Create Date: 2020-02-15 17:39:03.828352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702bc09c73f9'
down_revision = '4422792e6609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounter', sa.Column('pap_category', sa.Integer(), nullable=True))
    op.drop_column('encounter', 'number_of_paps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounter', sa.Column('number_of_paps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('encounter', 'pap_category')
    # ### end Alembic commands ###
