"""empty message

Revision ID: 86f6ff25c4ff
Revises: 8c950a9328b9
Create Date: 2020-04-11 12:38:09.052335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f6ff25c4ff'
down_revision = '8c950a9328b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_metadata',
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('metadata_date', sa.Date(), nullable=True),
    sa.Column('environment_time', sa.Time(), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('air_temp', sa.Float(precision=5), nullable=True),
    sa.Column('water_temp_surface', sa.Float(precision=5), nullable=True),
    sa.Column('water_temp_1_m', sa.Float(precision=5), nullable=True),
    sa.Column('water_temp_2_m', sa.Float(precision=5), nullable=True),
    sa.Column('water_temp_6_m', sa.Float(precision=5), nullable=True),
    sa.Column('water_temp_bottom', sa.Float(precision=5), nullable=True),
    sa.Column('salinity_surface', sa.Float(precision=5), nullable=True),
    sa.Column('salinity_1_m', sa.Float(precision=5), nullable=True),
    sa.Column('salinity_2_m', sa.Float(precision=5), nullable=True),
    sa.Column('salinity_6_m', sa.Float(precision=5), nullable=True),
    sa.Column('salinity_bottom', sa.Float(precision=5), nullable=True),
    sa.ForeignKeyConstraint(['metadata_id'], ['metadata.metadata_id'], ),
    sa.PrimaryKeyConstraint('metadata_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_metadata')
    # ### end Alembic commands ###
