"""empty message

Revision ID: 8c950a9328b9
Revises: 9d3676966b5b
Create Date: 2020-04-11 12:05:11.040877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c950a9328b9'
down_revision = '9d3676966b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beach_encounter', sa.Column('scanned', sa.Boolean(), nullable=True))
    op.add_column('beach_encounter', sa.Column('scanner_number', sa.String(length=30), nullable=True))
    op.add_column('beach_encounter', sa.Column('tag1', sa.String(length=30), nullable=True))
    op.add_column('beach_encounter', sa.Column('tag2', sa.String(length=30), nullable=True))
    op.add_column('beach_encounter', sa.Column('tag3', sa.String(length=30), nullable=True))
    op.add_column('beach_encounter', sa.Column('tag_scars', sa.String(length=20), nullable=True))
    op.add_column('lagoon_encounter', sa.Column('scanned', sa.Boolean(), nullable=True))
    op.add_column('lagoon_encounter', sa.Column('tag1', sa.String(length=30), nullable=True))
    op.add_column('lagoon_encounter', sa.Column('tag2', sa.String(length=30), nullable=True))
    op.add_column('lagoon_encounter', sa.Column('tag3', sa.String(length=30), nullable=True))
    op.add_column('lagoon_encounter', sa.Column('tag_scars', sa.String(length=20), nullable=True))
    op.drop_column('legacy', 'carap_w_oc_over_barnacles')
    op.drop_column('legacy', 'carap_l_oc_over_barnacles')
    op.drop_column('legacy', 'body_depth_over_barnacles')
    op.drop_column('legacy', 'sex')
    op.drop_column('legacy', 'plastron_l_over_barnacles')
    op.add_column('morphometrics', sa.Column('body_depth_over_barnacles', sa.Boolean(), nullable=True))
    op.add_column('morphometrics', sa.Column('curved_length_over_barnacles', sa.Boolean(), nullable=True))
    op.add_column('morphometrics', sa.Column('curved_width_over_barnacles', sa.Boolean(), nullable=True))
    op.add_column('morphometrics', sa.Column('plastron_length_over_barnacles', sa.Boolean(), nullable=True))
    op.add_column('offshore_encounter', sa.Column('magnet_off', sa.String(length=30), nullable=True))
    op.add_column('offshore_encounter', sa.Column('scanned', sa.Boolean(), nullable=True))
    op.add_column('offshore_encounter', sa.Column('tag1', sa.String(length=30), nullable=True))
    op.add_column('offshore_encounter', sa.Column('tag2', sa.String(length=30), nullable=True))
    op.drop_column('tag', 'scanned')
    op.drop_column('tag', 'scanner_number')
    op.drop_column('tag', 'tag_scars')
    op.drop_column('tag', 'magnet_off')
    op.add_column('trident_encounter', sa.Column('scanned', sa.Boolean(), nullable=True))
    op.add_column('trident_encounter', sa.Column('tag1', sa.String(length=30), nullable=True))
    op.add_column('trident_encounter', sa.Column('tag2', sa.String(length=30), nullable=True))
    op.add_column('trident_encounter', sa.Column('tag3', sa.String(length=30), nullable=True))
    op.add_column('trident_encounter', sa.Column('tag_scars', sa.String(length=20), nullable=True))
    op.add_column('turtle', sa.Column('sex', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turtle', 'sex')
    op.drop_column('trident_encounter', 'tag_scars')
    op.drop_column('trident_encounter', 'tag3')
    op.drop_column('trident_encounter', 'tag2')
    op.drop_column('trident_encounter', 'tag1')
    op.drop_column('trident_encounter', 'scanned')
    op.add_column('tag', sa.Column('magnet_off', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('tag_scars', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('scanner_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('scanned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('offshore_encounter', 'tag2')
    op.drop_column('offshore_encounter', 'tag1')
    op.drop_column('offshore_encounter', 'scanned')
    op.drop_column('offshore_encounter', 'magnet_off')
    op.drop_column('morphometrics', 'plastron_length_over_barnacles')
    op.drop_column('morphometrics', 'curved_width_over_barnacles')
    op.drop_column('morphometrics', 'curved_length_over_barnacles')
    op.drop_column('morphometrics', 'body_depth_over_barnacles')
    op.add_column('legacy', sa.Column('plastron_l_over_barnacles', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('legacy', sa.Column('sex', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('legacy', sa.Column('body_depth_over_barnacles', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('legacy', sa.Column('carap_l_oc_over_barnacles', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('legacy', sa.Column('carap_w_oc_over_barnacles', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('lagoon_encounter', 'tag_scars')
    op.drop_column('lagoon_encounter', 'tag3')
    op.drop_column('lagoon_encounter', 'tag2')
    op.drop_column('lagoon_encounter', 'tag1')
    op.drop_column('lagoon_encounter', 'scanned')
    op.drop_column('beach_encounter', 'tag_scars')
    op.drop_column('beach_encounter', 'tag3')
    op.drop_column('beach_encounter', 'tag2')
    op.drop_column('beach_encounter', 'tag1')
    op.drop_column('beach_encounter', 'scanner_number')
    op.drop_column('beach_encounter', 'scanned')
    # ### end Alembic commands ###
