"""empty message

Revision ID: 97cb6188391f
Revises: caccede2e007
Create Date: 2020-02-12 20:10:16.960451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cb6188391f'
down_revision = 'caccede2e007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paps')
    op.add_column('encounter', sa.Column('number_of_paps', sa.Integer(), nullable=True))
    op.add_column('encounter', sa.Column('pap_photos', sa.Boolean(), nullable=True))
    op.add_column('encounter', sa.Column('paps_present', sa.Boolean(), nullable=True))
    op.add_column('encounter', sa.Column('paps_regression', sa.String(length=40), nullable=True))
    op.add_column('encounter', sa.Column('photos', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounter', 'photos')
    op.drop_column('encounter', 'paps_regression')
    op.drop_column('encounter', 'paps_present')
    op.drop_column('encounter', 'pap_photos')
    op.drop_column('encounter', 'number_of_paps')
    op.create_table('paps',
    sa.Column('pap_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encounter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paps_present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('number_of_paps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paps_regression', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('photos', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pap_photos', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.encounter_id'], name='paps_encounter_id_fkey'),
    sa.PrimaryKeyConstraint('pap_id', name='paps_pkey')
    )
    # ### end Alembic commands ###
