"""empty message

Revision ID: 9d3676966b5b
Revises: cf05f73b81e1
Create Date: 2020-04-09 18:28:06.342877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3676966b5b'
down_revision = 'cf05f73b81e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_encounter',
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('encounter_date', sa.Date(), nullable=True),
    sa.Column('encounter_time', sa.Time(), nullable=True),
    sa.Column('investigated_by', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paps_present', sa.Boolean(), nullable=True),
    sa.Column('pap_category', sa.Integer(), nullable=True),
    sa.Column('paps_regressed', sa.String(length=40), nullable=True),
    sa.Column('pap_photo', sa.Boolean(), nullable=True),
    sa.Column('leeches', sa.Boolean(), nullable=True),
    sa.Column('leeches_where', sa.Text(), nullable=True),
    sa.Column('leech_eggs', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.encounter_id'], ),
    sa.PrimaryKeyConstraint('encounter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_encounter')
    # ### end Alembic commands ###
