"""empty message

Revision ID: a153b825e0f6
Revises: 5b9fc7ca2214
Create Date: 2020-02-12 19:27:08.761527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a153b825e0f6'
down_revision = '5b9fc7ca2214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounter', 'species')
    op.add_column('turtle', sa.Column('species', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turtle', 'species')
    op.add_column('encounter', sa.Column('species', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
