"""empty message

Revision ID: c02957d2cb8a
Revises: fa79dc13ca39
Create Date: 2020-03-26 00:12:58.755205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02957d2cb8a'
down_revision = 'fa79dc13ca39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounter', sa.Column('filename', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounter', 'filename')
    # ### end Alembic commands ###
