"""empty message

Revision ID: c442e5d4311a
Revises: cf541ea02b2c
Create Date: 2020-03-29 22:05:01.274279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c442e5d4311a'
down_revision = 'cf541ea02b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('magnet_off', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'magnet_off')
    # ### end Alembic commands ###
