"""empty message

Revision ID: cf05f73b81e1
Revises: c442e5d4311a
Create Date: 2020-04-04 22:22:55.062192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf05f73b81e1'
down_revision = 'c442e5d4311a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy',
    sa.Column('legacy_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('recapture_linear_dates', sa.Text(), nullable=True),
    sa.Column('pap_mapped', sa.Boolean(), nullable=True),
    sa.Column('papilloma_description', sa.Text(), nullable=True),
    sa.Column('disposal_of_specimen', sa.Text(), nullable=True),
    sa.Column('stake_summary', sa.Text(), nullable=True),
    sa.Column('survery_full_location', sa.Float(precision=5), nullable=True),
    sa.Column('clutch_moved', sa.Text(), nullable=True),
    sa.Column('clutch_fate', sa.Text(), nullable=True),
    sa.Column('eggs_yolked', sa.Integer(), nullable=True),
    sa.Column('eggs_broken', sa.Integer(), nullable=True),
    sa.Column('eggs_yolkless', sa.Integer(), nullable=True),
    sa.Column('eggs_research', sa.Integer(), nullable=True),
    sa.Column('in_place_foil', sa.Boolean(), nullable=True),
    sa.Column('in_place_metal', sa.Boolean(), nullable=True),
    sa.Column('carap_l_oc_over_barnacles', sa.Boolean(), nullable=True),
    sa.Column('carap_l_greatest', sa.Float(precision=5), nullable=True),
    sa.Column('carap_w_oc_over_barnacles', sa.Boolean(), nullable=True),
    sa.Column('plastron_l_over_barnacles', sa.Boolean(), nullable=True),
    sa.Column('body_depth_over_barnacles', sa.Boolean(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('cloaca_temp', sa.Float(precision=5), nullable=True),
    sa.Column('interanal_scute', sa.Text(), nullable=True),
    sa.Column('date_laid', sa.Date(), nullable=True),
    sa.Column('c1_embryo', sa.Integer(), nullable=True),
    sa.Column('c2_fetus', sa.Integer(), nullable=True),
    sa.Column('c6_infertile_eggs', sa.Integer(), nullable=True),
    sa.Column('d1_research', sa.Integer(), nullable=True),
    sa.Column('d2_poached', sa.Integer(), nullable=True),
    sa.Column('e2_washout', sa.Integer(), nullable=True),
    sa.Column('e3_inundated', sa.Integer(), nullable=True),
    sa.Column('d_nest_disturbed_summary', sa.Text(), nullable=True),
    sa.Column('nest_data_collection_problems', sa.Text(), nullable=True),
    sa.Column('wind_speed_min_mph', sa.Float(precision=5), nullable=True),
    sa.Column('wind_speed_max_mph', sa.Float(precision=5), nullable=True),
    sa.Column('wind_speed_min_mps', sa.Float(precision=5), nullable=True),
    sa.Column('wind_speed_max_mps', sa.Float(precision=5), nullable=True),
    sa.Column('depth', sa.Float(precision=5), nullable=True),
    sa.Column('length_units', sa.Text(), nullable=True),
    sa.Column('water_temp_3', sa.Float(precision=5), nullable=True),
    sa.Column('salinity_3', sa.Float(precision=5), nullable=True),
    sa.Column('secchi_depth', sa.Float(precision=5), nullable=True),
    sa.Column('secchi_distance_from_shore', sa.Float(precision=5), nullable=True),
    sa.Column('time_text_high_tide', sa.Time(), nullable=True),
    sa.Column('time_text_low_tide', sa.Time(), nullable=True),
    sa.Column('notes_environment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.encounter_id'], ),
    sa.PrimaryKeyConstraint('legacy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legacy')
    # ### end Alembic commands ###
