"""empty message

Revision ID: cf541ea02b2c
Revises: f39f2d282d5e
Create Date: 2020-03-29 12:20:26.835140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf541ea02b2c'
down_revision = 'f39f2d282d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_set',
    sa.Column('filter_set_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('filter_set_name', sa.String(length=50), nullable=True),
    sa.Column('filter_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('filter_set_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter_set')
    # ### end Alembic commands ###
