"""empty message

Revision ID: ee5d36df4ab6
Revises: 7b3f09b3e3aa
Create Date: 2020-03-23 13:57:03.544211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5d36df4ab6'
down_revision = '7b3f09b3e3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clutch_turtle_id_fkey', 'clutch', type_='foreignkey')
    op.drop_column('clutch', 'turtle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clutch', sa.Column('turtle_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('clutch_turtle_id_fkey', 'clutch', 'turtle', ['turtle_id'], ['turtle_id'])
    # ### end Alembic commands ###
