"""empty message

Revision ID: fa79dc13ca39
Revises: ee5d36df4ab6
Create Date: 2020-03-24 18:24:15.251136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa79dc13ca39'
down_revision = 'ee5d36df4ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_survey', sa.Column('km_8_05n_55_t_cc_nests', sa.Integer(), nullable=True))
    op.drop_column('big_survey', 'km_8_05n_55__cc_nests')
    op.add_column('emergence', sa.Column('big_survey_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'emergence', 'big_survey', ['big_survey_id'], ['big_survey_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emergence', type_='foreignkey')
    op.drop_column('emergence', 'big_survey_id')
    op.add_column('big_survey', sa.Column('km_8_05n_55__cc_nests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('big_survey', 'km_8_05n_55_t_cc_nests')
    # ### end Alembic commands ###
