"""empty message

Revision ID: fcafc027ced1
Revises: a500a1bbf887
Create Date: 2020-02-15 11:02:11.489569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcafc027ced1'
down_revision = 'a500a1bbf887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clutch', sa.Column('eggs_addled', sa.Integer(), nullable=True))
    op.drop_column('clutch', 'eggs_eggs')
    op.add_column('turtle', sa.Column('old_turtle_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turtle', 'old_turtle_id')
    op.add_column('clutch', sa.Column('eggs_eggs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('clutch', 'eggs_addled')
    # ### end Alembic commands ###
